mode: exp
preserve_checkpoints: True
single_HP: False
cfg_path: null # full path to model config
tuning_holdout: False # for UKB
tuning_split: null

n_trials: 10
n_splits: 5
max_epochs: 400
batch_size: 64
patience: 30